### ISSUE TITLE
Caching of bad jackson metadata file breaks builds

### ISSUE THREAD

**Issue by jsimone** [heroku/s3pository#11]
This issue still comes up from time to time: http://stackoverflow.com/questions/12651959/maven-build-error-no-versions-available-for-org-codehaus-jacksonjackson-core-as

We should either specifically ignore this file or possibly drop the cache interval for metadata files so that the issue is less lasting when it occurs.

**Comment by joshwlewis** [comment]
Closing as this service is being retired.
