### ISSUE TITLE
Allow requests to base path of proxied repositories

### ISSUE THREAD

**Issue by zeke** [heroku/s3pository#15]
I want to hit this:

http://s3pository.heroku.com/node/

and see this:

http://nodejs.org/dist/

but this:

https://github.com/heroku/s3pository/blob/master/src/main/scala/com/heroku/s3pository/ProxyService.scala#L424

I'm okay with the mimetype being wrong/different, causing the browser to download the file instead of displaying it. I just want to curl that endpoint.

**Comment by joshwlewis** [comment]
Closing as this service is being retired.
