### ISSUE TITLE
Add scala-tools snapshots to sonatype oss snapshots OR remove from buildpack resolver list

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/s3pository#5]
Pull request #4 fixed the issue with correcting the path to scala-tools releases on sonatype oss, but did not do the same for snapshots because we are already proxying  https://oss.sonatype.org/content/repositories/snapshots/, but with filters for only com.force and com.heroku. This issue is to either include the scala-tools snapshots or just completely remove it from the buildpack's list of resolvers.

**Comment by joshwlewis** [comment]
Closing as this service is being retired.
